import Head from 'next/head'
import Script from 'next/script'

import { useMediaQuery } from 'react-responsive'

import ClientOnly from '@/components/layouts/client_only'
import ComponentIsDeskatop from '@/components/layouts/desktop'

export default function Home() {
  const is_desktop = useMediaQuery({
    minWidth: 320
  })

  return (
    <>
      <Head>
        <title>Alejo Beltran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css"></link>
        <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css"/>
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ClientOnly>
          {
            is_desktop && <ComponentIsDeskatop/>
          }
          <Script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></Script>
          <Script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></Script>
        </ClientOnly>
      </main>
    </>
  )
}
