import Head from 'next/head'
import { useMediaQuery } from 'react-responsive'

import ComponentIsDeskatop from '@/components/layouts/desktop'
import ComponentIsTablet from '@/components/layouts/tablet'
import ComponentIsMobile from '@/components/layouts/mobile'

export default function Home() {
  const is_desktop = useMediaQuery({
    query: '(min-width: 1280px)'
  })
  const is_tablet = useMediaQuery({
    minWidth: 600, 
    maxWidth: 1280
  })
  const is_mobile = useMediaQuery({
    minWidth: 320, 
    maxWidth: 600
  })

  return (
    <>
      <Head>
        <title>Alejo Beltran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
      </Head>
      <main>
        {
          is_desktop? <ComponentIsDeskatop/> :
          is_tablet?  <ComponentIsTablet/> :
          is_mobile?  <ComponentIsMobile/> : ""
        }
      </main>
    </>
  )
}
